### ISSUE TITLE
Node ES modules can't import crank

### ISSUE THREAD

**Issue by dfabulich** [bikeshaving/crank#87]
To reproduce:

I'm running node v14.1.0.

```bash
mkdir testesm
cd testesm
npm init -y
npm i @bikeshaving/crank
cat <<EOF > index.mjs
import {createElement} from "@bikeshaving/crank";
import {renderer} from "@bikeshaving/crank/html";

console.log(renderer.render(createElement("div", null, "Hello world")));
EOF
node index.mjs
```

Expected: The console should show `<div>Hello world</div>`

Actual:
```
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/private/tmp/tp/testesm/node_modules/@bikeshaving/crank/html' imported from /private/tmp/tp/testesm/index.mjs
    at finalizeResolution (internal/modules/esm/resolve.js:272:11)
    at packageResolve (internal/modules/esm/resolve.js:607:14)
    at moduleResolve (internal/modules/esm/resolve.js:646:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:692:13)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by brainkim** [comment]
Sorry to hear about this. Confirming this is an issue with node.js versions 12/13. I am consistently infuriated by how senseless and arcane node.js ESModule support is and can’t seem to figure it out at the moment (1:53AM Saturday for me right now). For some reason, I can’t even import the cjs versions. Is there a resource you know of which just tells me how to support node.js 13 for esmodules?
